apiVersion: v1
appVersion: "0.9.2"
description: A Helm chart for deploying Python Celery to Kubernetes
name: celery-flower
version: 0.2.3
icon: https://en.wikipedia.org/wiki/Celery_(software)#/media/File:Celery_logo.png
sources:
  - https://github.com/introspectdata/docker-celery-flower
  - https://github.com/mher/flower
  - https://github.com/crgwbr/docker-celery-flower
maintainers: # (optional)
  - name: Patrick McClory
    email: pmdev@introspectdata.com
    url: https://github.com/mcclory
