# Default values for celery-flower.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: mher/flower
  tag: latest
  pullPolicy: Always

appName: ""

service:
  type: ClusterIP
  port: 5555

# This gets put into the config map... and referenced for ingress so it's separate from the environment variable set itself...
applicationPort: 5555

celery:
  broker: ""
  broker_api: ""
  result_backend: ""
# Add non-secret configs via key-value pairs that will get shoved into a config map and referenced via `envFrom`
# use this to set arbitrary environment variables for Flower
envVars: {}
#  FLOWER_VARIABLE: value

# Add other external secrets as necessary... just in case they're useful
secretVars: {}
#  FLOWER_VARIABLE: value

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx-private
    # nginx.ingress.kubernetes.io/auth-signin: https://$host/oauth2/start
    # nginx.ingress.kubernetes.io/auth-url: https://$host/oauth2/auth
    # kubernetes.io/tls-acme: "true"
    # ingress.kubernetes.io/force-ssl-redirect: "true"
    # nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Request-User, X-Auth-Request-Email
  path: /
  hosts: []
  #  - flower.domain.tld
  tls: []
  #  - secretName: flower-domain.tld
  #    hosts:
  #      - flower.domain.tld

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
