---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "celery-flower.fullname" . }}
  labels:
    app: {{ template "celery-flower.name" . }}
    chart: {{ template "celery-flower.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- if .Values.envVars }}
{{- range $index, $index_value := .Values.envValues }}
  {{ $index }}: {{ $index_value | quote }}
{{- end }}
{{- end }}
